# Generated by Django 3.1.7 on 2021-03-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationrecord',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='navigationrecord',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='navigationrecord',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
