# Generated by Django 3.1.7 on 2021-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20210317_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
